# -*- coding: utf-8 -*-
"""
/***************************************************************************
 changedetection
                                 A QGIS plugin
 Algorithm gets 2 folders with images, each image pair should have the same name, does change detection on them and returns change map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-02-19
        copyright            : (C) 2024 by CAST
        email                : yesayan.svetlana@student.rau.am
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load changedetection class from file changedetection.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ChangeDetection import changedetection
    return changedetection(iface)
